name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - master
      - principal
  pull_request:
    branches:
      - main
      - master
      - principal

jobs:
  sonarcloud:
    name: Análisis de código estático
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Análisis con SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
